version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 7889:80
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  client:
    image: ghcr.io/kraanter/peoplepartyportal:staging
  api:
    image: ghcr.io/kraanter/peoplepartybackend:staging
    restart: unless-stopped
