#ifndef PEOPLEPARTY_BACKEND_MEMORYMIXER_CARD_H
#define PEOPLEPARTY_BACKEND_MEMORYMIXER_CARD_H

enum MemoryMixer_card {
    CARD_BALLOON,
    CARD_CAKE,
    CARD_CONFETTI,
    CARD_CONFETTI2,
    CARD_SMILEY,
    CARD_CANDLE,
    CARD_HAT,
    CARD_EMPTY,
};

#endif //PEOPLEPARTY_BACKEND_MEMORYMIXER_CARD_H