// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GameStatePayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameStatePayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameStatePayload(bb:flatbuffers.ByteBuffer, obj?:GameStatePayload):GameStatePayload {
  return (obj || new GameStatePayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameStatePayload(bb:flatbuffers.ByteBuffer, obj?:GameStatePayload):GameStatePayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameStatePayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startGameStatePayload(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endGameStatePayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameStatePayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  GameStatePayload.startGameStatePayload(builder);
  return GameStatePayload.endGameStatePayload(builder);
}
}
