// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class BusinessBailoutPlayerInputPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BusinessBailoutPlayerInputPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBusinessBailoutPlayerInputPayload(bb:flatbuffers.ByteBuffer, obj?:BusinessBailoutPlayerInputPayload):BusinessBailoutPlayerInputPayload {
  return (obj || new BusinessBailoutPlayerInputPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBusinessBailoutPlayerInputPayload(bb:flatbuffers.ByteBuffer, obj?:BusinessBailoutPlayerInputPayload):BusinessBailoutPlayerInputPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BusinessBailoutPlayerInputPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lock():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startBusinessBailoutPlayerInputPayload(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLock(builder:flatbuffers.Builder, lock:boolean) {
  builder.addFieldInt8(0, +lock, +false);
}

static endBusinessBailoutPlayerInputPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBusinessBailoutPlayerInputPayload(builder:flatbuffers.Builder, lock:boolean):flatbuffers.Offset {
  BusinessBailoutPlayerInputPayload.startBusinessBailoutPlayerInputPayload(builder);
  BusinessBailoutPlayerInputPayload.addLock(builder, lock);
  return BusinessBailoutPlayerInputPayload.endBusinessBailoutPlayerInputPayload(builder);
}
}
