// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CountingClientData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CountingClientData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCountingClientData(bb:flatbuffers.ByteBuffer, obj?:CountingClientData):CountingClientData {
  return (obj || new CountingClientData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCountingClientData(bb:flatbuffers.ByteBuffer, obj?:CountingClientData):CountingClientData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CountingClientData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

newInt():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

static startCountingClientData(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addNewInt(builder:flatbuffers.Builder, newInt:number) {
  builder.addFieldInt16(0, newInt, 0);
}

static endCountingClientData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCountingClientData(builder:flatbuffers.Builder, newInt:number):flatbuffers.Offset {
  CountingClientData.startCountingClientData(builder);
  CountingClientData.addNewInt(builder, newInt);
  return CountingClientData.endCountingClientData(builder);
}
}
