// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum FB_RPSChoice {
  NONE = 0,
  ROCK = 1,
  PAPER = 2,
  SCISSORS = 3
}
