// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum FB_RPSChoice {
  ROCK = 0,
  PAPER = 1,
  SCISSORS = 2,
  NONE = 3
}
