// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum GameStateType {
  BusinessBailoutHost = 0,
  BusinessBailoutPlayer = 1,
  BusinessBailoutPlayerInput = 2,
  CrazyCountingPlayerUpdate = 3,
  CrazyCountingHostEntities = 4,
  CrazyCountingPlayerInput = 5,
  CrazyCountingResult = 6,
  MiniGameIntroduction = 7
}
