// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum GameStateType {
  CrazyCountingHostEntities = 0,
  CrazyCountingPlayerInput = 1,
  CrazyCountingPlayerUpdate = 2,
  CrazyCountingResult = 3,
  MemoryMixerGrid = 4,
  MemoryMixerPlayerInput = 5,
  MemoryMixerPlayerSubmitted = 6,
  MiniGameIntroduction = 7
}
