// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum GameStateType {
  BusinessBailoutHost = 0,
  BusinessBailoutPlayerInput = 1,
  BusinessBailoutPlayer = 2,
  BusinessBailoutResult = 3,
  CrazyCountingHostEntities = 4,
  CrazyCountingPlayerInput = 5,
  CrazyCountingPlayerUpdate = 6,
  CrazyCountingResult = 7,
  LaunchPartyLights = 8,
  LaunchPartyPlayerInput = 9,
  LaunchPartyPlayerTime = 10,
  LaunchPartyResult = 11,
  MemoryMixerGrid = 12,
  MemoryMixerPlayerInput = 13,
  MemoryMixerPlayerSubmitted = 14,
  MemoryMixerResult = 15,
  MemoryMixerRoundResult = 16,
  MiniGameIntroduction = 17,
  RightOnTime = 18,
  RightOnTimeResult = 19,
  RightOnTimeRoundResult = 20,
  RPSBracketHost = 21,
  RPSBracketPlayerInput = 22,
  RPSBracketPlayer = 23
}
