// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum IconType {
  BALLOON = 0,
  CAKE = 1,
  CONFETTI = 2,
  CONFETTI2 = 3,
  SMILEY = 4
}
