// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class JoinPayloadType {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):JoinPayloadType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsJoinPayloadType(bb:flatbuffers.ByteBuffer, obj?:JoinPayloadType):JoinPayloadType {
  return (obj || new JoinPayloadType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsJoinPayloadType(bb:flatbuffers.ByteBuffer, obj?:JoinPayloadType):JoinPayloadType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new JoinPayloadType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

success():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startJoinPayloadType(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSuccess(builder:flatbuffers.Builder, success:boolean) {
  builder.addFieldInt8(0, +success, +false);
}

static endJoinPayloadType(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createJoinPayloadType(builder:flatbuffers.Builder, success:boolean):flatbuffers.Offset {
  JoinPayloadType.startJoinPayloadType(builder);
  JoinPayloadType.addSuccess(builder, success);
  return JoinPayloadType.endJoinPayloadType(builder);
}
}
