// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class LaunchPartyPlayerTimePayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LaunchPartyPlayerTimePayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLaunchPartyPlayerTimePayload(bb:flatbuffers.ByteBuffer, obj?:LaunchPartyPlayerTimePayload):LaunchPartyPlayerTimePayload {
  return (obj || new LaunchPartyPlayerTimePayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLaunchPartyPlayerTimePayload(bb:flatbuffers.ByteBuffer, obj?:LaunchPartyPlayerTimePayload):LaunchPartyPlayerTimePayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LaunchPartyPlayerTimePayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

time():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startLaunchPartyPlayerTimePayload(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTime(builder:flatbuffers.Builder, time:bigint) {
  builder.addFieldInt64(0, time, BigInt('0'));
}

static endLaunchPartyPlayerTimePayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLaunchPartyPlayerTimePayload(builder:flatbuffers.Builder, time:bigint):flatbuffers.Offset {
  LaunchPartyPlayerTimePayload.startLaunchPartyPlayerTimePayload(builder);
  LaunchPartyPlayerTimePayload.addTime(builder, time);
  return LaunchPartyPlayerTimePayload.endLaunchPartyPlayerTimePayload(builder);
}
}
