// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class LaunchPartyLightsPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LaunchPartyLightsPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLaunchPartyLightsPayload(bb:flatbuffers.ByteBuffer, obj?:LaunchPartyLightsPayload):LaunchPartyLightsPayload {
  return (obj || new LaunchPartyLightsPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLaunchPartyLightsPayload(bb:flatbuffers.ByteBuffer, obj?:LaunchPartyLightsPayload):LaunchPartyLightsPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LaunchPartyLightsPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lights():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

static startLaunchPartyLightsPayload(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLights(builder:flatbuffers.Builder, lights:number) {
  builder.addFieldInt16(0, lights, 0);
}

static endLaunchPartyLightsPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLaunchPartyLightsPayload(builder:flatbuffers.Builder, lights:number):flatbuffers.Offset {
  LaunchPartyLightsPayload.startLaunchPartyLightsPayload(builder);
  LaunchPartyLightsPayload.addLights(builder, lights);
  return LaunchPartyLightsPayload.endLaunchPartyLightsPayload(builder);
}
}
