// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { LeaderboardHostSkipPayload } from './leaderboard-host-skip-payload.js';
import { LeaderboardInformationPayload } from './leaderboard-information-payload.js';


export enum LeaderboardPayload {
  NONE = 0,
  LeaderboardInformationPayload = 1,
  LeaderboardHostSkipPayload = 2
}

export function unionToLeaderboardPayload(
  type: LeaderboardPayload,
  accessor: (obj:LeaderboardHostSkipPayload|LeaderboardInformationPayload) => LeaderboardHostSkipPayload|LeaderboardInformationPayload|null
): LeaderboardHostSkipPayload|LeaderboardInformationPayload|null {
  switch(LeaderboardPayload[type]) {
    case 'NONE': return null; 
    case 'LeaderboardInformationPayload': return accessor(new LeaderboardInformationPayload())! as LeaderboardInformationPayload;
    case 'LeaderboardHostSkipPayload': return accessor(new LeaderboardHostSkipPayload())! as LeaderboardHostSkipPayload;
    default: return null;
  }
}

export function unionListToLeaderboardPayload(
  type: LeaderboardPayload, 
  accessor: (index: number, obj:LeaderboardHostSkipPayload|LeaderboardInformationPayload) => LeaderboardHostSkipPayload|LeaderboardInformationPayload|null, 
  index: number
): LeaderboardHostSkipPayload|LeaderboardInformationPayload|null {
  switch(LeaderboardPayload[type]) {
    case 'NONE': return null; 
    case 'LeaderboardInformationPayload': return accessor(index, new LeaderboardInformationPayload())! as LeaderboardInformationPayload;
    case 'LeaderboardHostSkipPayload': return accessor(index, new LeaderboardHostSkipPayload())! as LeaderboardHostSkipPayload;
    default: return null;
  }
}
