// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MessageType {
  Host = 0,
  Join = 1,
  MiniGame = 2,
  PartyPrep = 3
}
