// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FBPlayer } from './fbplayer.js';


export class PartyPrepHostInformationPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PartyPrepHostInformationPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPartyPrepHostInformationPayload(bb:flatbuffers.ByteBuffer, obj?:PartyPrepHostInformationPayload):PartyPrepHostInformationPayload {
  return (obj || new PartyPrepHostInformationPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPartyPrepHostInformationPayload(bb:flatbuffers.ByteBuffer, obj?:PartyPrepHostInformationPayload):PartyPrepHostInformationPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PartyPrepHostInformationPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

roomId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

players(index: number, obj?:FBPlayer):FBPlayer|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new FBPlayer()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

playersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPartyPrepHostInformationPayload(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addRoomId(builder:flatbuffers.Builder, roomId:bigint) {
  builder.addFieldInt64(0, roomId, BigInt('0'));
}

static addPlayers(builder:flatbuffers.Builder, playersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, playersOffset, 0);
}

static createPlayersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPlayersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPartyPrepHostInformationPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPartyPrepHostInformationPayload(builder:flatbuffers.Builder, roomId:bigint, playersOffset:flatbuffers.Offset):flatbuffers.Offset {
  PartyPrepHostInformationPayload.startPartyPrepHostInformationPayload(builder);
  PartyPrepHostInformationPayload.addRoomId(builder, roomId);
  PartyPrepHostInformationPayload.addPlayers(builder, playersOffset);
  return PartyPrepHostInformationPayload.endPartyPrepHostInformationPayload(builder);
}
}
