// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { PartyPrepHostInformationPayload } from './party-prep-host-information-payload.js';
import { PartyPrepHostStartGamePayload } from './party-prep-host-start-game-payload.js';
import { PartyPrepPlayerInformationPayload } from './party-prep-player-information-payload.js';


export enum PartyPrepPayload {
  NONE = 0,
  PartyPrepHostInformationPayload = 1,
  PartyPrepHostStartGamePayload = 2,
  PartyPrepPlayerInformationPayload = 3
}

export function unionToPartyPrepPayload(
  type: PartyPrepPayload,
  accessor: (obj:PartyPrepHostInformationPayload|PartyPrepHostStartGamePayload|PartyPrepPlayerInformationPayload) => PartyPrepHostInformationPayload|PartyPrepHostStartGamePayload|PartyPrepPlayerInformationPayload|null
): PartyPrepHostInformationPayload|PartyPrepHostStartGamePayload|PartyPrepPlayerInformationPayload|null {
  switch(PartyPrepPayload[type]) {
    case 'NONE': return null; 
    case 'PartyPrepHostInformationPayload': return accessor(new PartyPrepHostInformationPayload())! as PartyPrepHostInformationPayload;
    case 'PartyPrepHostStartGamePayload': return accessor(new PartyPrepHostStartGamePayload())! as PartyPrepHostStartGamePayload;
    case 'PartyPrepPlayerInformationPayload': return accessor(new PartyPrepPlayerInformationPayload())! as PartyPrepPlayerInformationPayload;
    default: return null;
  }
}

export function unionListToPartyPrepPayload(
  type: PartyPrepPayload, 
  accessor: (index: number, obj:PartyPrepHostInformationPayload|PartyPrepHostStartGamePayload|PartyPrepPlayerInformationPayload) => PartyPrepHostInformationPayload|PartyPrepHostStartGamePayload|PartyPrepPlayerInformationPayload|null, 
  index: number
): PartyPrepHostInformationPayload|PartyPrepHostStartGamePayload|PartyPrepPlayerInformationPayload|null {
  switch(PartyPrepPayload[type]) {
    case 'NONE': return null; 
    case 'PartyPrepHostInformationPayload': return accessor(index, new PartyPrepHostInformationPayload())! as PartyPrepHostInformationPayload;
    case 'PartyPrepHostStartGamePayload': return accessor(index, new PartyPrepHostStartGamePayload())! as PartyPrepHostStartGamePayload;
    case 'PartyPrepPlayerInformationPayload': return accessor(index, new PartyPrepPlayerInformationPayload())! as PartyPrepPlayerInformationPayload;
    default: return null;
  }
}
