// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum PartyPrepType {
  PartyPrepHostInformation = 0,
  PartyPrepHostStartGame = 1,
  PartyPrepPlayerInformation = 2,
  PartyPrepSettingsInformation = 3,
  PartyPrepSettingsRounds = 4,
  PartyPrepSettingsMiniGame = 5
}
