// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PlayerBailout {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerBailout {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerBailout(bb:flatbuffers.ByteBuffer, obj?:PlayerBailout):PlayerBailout {
  return (obj || new PlayerBailout()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerBailout(bb:flatbuffers.ByteBuffer, obj?:PlayerBailout):PlayerBailout {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerBailout()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

time():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startPlayerBailout(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addTime(builder:flatbuffers.Builder, time:number) {
  builder.addFieldInt32(1, time, 0);
}

static endPlayerBailout(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerBailout(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, time:number):flatbuffers.Offset {
  PlayerBailout.startPlayerBailout(builder);
  PlayerBailout.addName(builder, nameOffset);
  PlayerBailout.addTime(builder, time);
  return PlayerBailout.endPlayerBailout(builder);
}
}
