// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FB_RPSMatch } from './fb-rpsmatch.js';


export class RPSBracketHostPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RPSBracketHostPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRPSBracketHostPayload(bb:flatbuffers.ByteBuffer, obj?:RPSBracketHostPayload):RPSBracketHostPayload {
  return (obj || new RPSBracketHostPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRPSBracketHostPayload(bb:flatbuffers.ByteBuffer, obj?:RPSBracketHostPayload):RPSBracketHostPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RPSBracketHostPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

matches(index: number, obj?:FB_RPSMatch):FB_RPSMatch|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new FB_RPSMatch()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

matchesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startRPSBracketHostPayload(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMatches(builder:flatbuffers.Builder, matchesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, matchesOffset, 0);
}

static createMatchesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMatchesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endRPSBracketHostPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRPSBracketHostPayload(builder:flatbuffers.Builder, matchesOffset:flatbuffers.Offset):flatbuffers.Offset {
  RPSBracketHostPayload.startRPSBracketHostPayload(builder);
  RPSBracketHostPayload.addMatches(builder, matchesOffset);
  return RPSBracketHostPayload.endRPSBracketHostPayload(builder);
}
}
